# -*- coding: utf-8 -*-
import datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models


class Migration(SchemaMigration):

    def forwards(self, orm):
        # Adding model 'Experiment'
        db.create_table('eyevacs_experiment', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('name', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('language', self.gf('django.db.models.fields.CharField')(max_length=2)),
            ('info', self.gf('django.db.models.fields.TextField')(blank=True)),
        ))
        db.send_create_signal('eyevacs', ['Experiment'])

        # Adding model 'Pub'
        db.create_table('eyevacs_pub', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('experiment', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['eyevacs.Experiment'])),
            ('sessionid', self.gf('django.db.models.fields.CharField')(max_length=150)),
            ('csrftoken', self.gf('django.db.models.fields.CharField')(max_length=150)),
            ('ct_size', self.gf('django.db.models.fields.IntegerField')()),
            ('hard_id', self.gf('django.db.models.fields.IntegerField')()),
            ('def_group', self.gf('django.db.models.fields.IntegerField')()),
            ('override_group', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('create_time', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime.now, blank=True)),
        ))
        db.send_create_signal('eyevacs', ['Pub'])

        # Adding model 'Attribute'
        db.create_table('eyevacs_attribute', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('name', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('name_en', self.gf('django.db.models.fields.CharField')(max_length=100, null=True, blank=True)),
            ('name_de', self.gf('django.db.models.fields.CharField')(max_length=100, null=True, blank=True)),
            ('exp_setup', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['eyevacs.Experiment'])),
            ('position', self.gf('django.db.models.fields.SmallIntegerField')()),
        ))
        db.send_create_signal('eyevacs', ['Attribute'])

        # Adding model 'Level'
        db.create_table('eyevacs_level', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('link_attribute', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['eyevacs.Attribute'])),
            ('name', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('name_en', self.gf('django.db.models.fields.CharField')(max_length=100, null=True, blank=True)),
            ('name_de', self.gf('django.db.models.fields.CharField')(max_length=100, null=True, blank=True)),
            ('value', self.gf('django.db.models.fields.IntegerField')()),
        ))
        db.send_create_signal('eyevacs', ['Level'])

        # Adding model 'External_Source_Data'
        db.create_table('eyevacs_external_source_data', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('filetype', self.gf('django.db.models.fields.CharField')(max_length=5)),
            ('header', self.gf('django.db.models.fields.CharField')(max_length=200)),
            ('exp_name', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('experiment', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['eyevacs.Experiment'])),
            ('info', self.gf('django.db.models.fields.TextField')(blank=True)),
            ('range_start', self.gf('django.db.models.fields.IntegerField')(default=0)),
            ('range_end', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
        ))
        db.send_create_signal('eyevacs', ['External_Source_Data'])

        # Adding model 'External_Choice_Task'
        db.create_table('eyevacs_external_choice_task', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('id_hard', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ext_src_data', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['eyevacs.External_Source_Data'])),
            ('ext_src_data_name', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('amount', self.gf('django.db.models.fields.IntegerField')()),
            ('a1', self.gf('django.db.models.fields.CharField')(default='empty', max_length=15)),
            ('a2', self.gf('django.db.models.fields.CharField')(default='empty', max_length=15)),
            ('a3', self.gf('django.db.models.fields.CharField')(default='empty', max_length=15)),
            ('a4', self.gf('django.db.models.fields.CharField')(default='empty', max_length=15)),
            ('a5', self.gf('django.db.models.fields.CharField')(default='empty', max_length=15)),
            ('a6', self.gf('django.db.models.fields.CharField')(default='empty', max_length=15)),
            ('a7', self.gf('django.db.models.fields.CharField')(default='empty', max_length=15)),
            ('a8', self.gf('django.db.models.fields.CharField')(default='empty', max_length=15)),
            ('used', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('linked_pcpt', self.gf('django.db.models.fields.related.ForeignKey')(blank=True, related_name='Choice_TasksAsParticipant', null=True, to=orm['eyevacs.Participant'])),
            ('linked_pub', self.gf('django.db.models.fields.related.ForeignKey')(blank=True, related_name='Choice_TasksAsPub', null=True, to=orm['eyevacs.Pub'])),
            ('raw_src_line', self.gf('django.db.models.fields.CharField')(max_length=100)),
        ))
        db.send_create_signal('eyevacs', ['External_Choice_Task'])

        # Adding model 'External_Baseline_Choice_Task'
        db.create_table('eyevacs_external_baseline_choice_task', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('id_hard', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('task', self.gf('django.db.models.fields.IntegerField')()),
            ('ext_src_data', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['eyevacs.External_Source_Data'])),
            ('ext_src_data_name', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('amount', self.gf('django.db.models.fields.IntegerField')()),
            ('a1', self.gf('django.db.models.fields.CharField')(default='empty', max_length=15)),
            ('a2', self.gf('django.db.models.fields.CharField')(default='empty', max_length=15)),
            ('a3', self.gf('django.db.models.fields.CharField')(default='empty', max_length=15)),
            ('a4', self.gf('django.db.models.fields.CharField')(default='empty', max_length=15)),
            ('a5', self.gf('django.db.models.fields.CharField')(default='empty', max_length=15)),
            ('used', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('linked_pcpt', self.gf('django.db.models.fields.related.ForeignKey')(blank=True, related_name='Baseline_Choice_TasksAsParticipant', null=True, to=orm['eyevacs.Participant'])),
            ('linked_pub', self.gf('django.db.models.fields.related.ForeignKey')(blank=True, related_name='Baseline_Choice_TasksAsPub', null=True, to=orm['eyevacs.Pub'])),
            ('raw_src_line', self.gf('django.db.models.fields.CharField')(max_length=100)),
        ))
        db.send_create_signal('eyevacs', ['External_Baseline_Choice_Task'])

        # Adding model 'External_Order_Scale'
        db.create_table('eyevacs_external_order_scale', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('id_hard', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('scale_rnd_order_ext', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('source_file', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['eyevacs.External_Source_Data'], null=True, blank=True)),
            ('linked_pcpt', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['eyevacs.Participant'], null=True, blank=True)),
            ('linked_pub', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['eyevacs.Pub'], null=True, blank=True)),
            ('used', self.gf('django.db.models.fields.BooleanField')(default=False)),
        ))
        db.send_create_signal('eyevacs', ['External_Order_Scale'])

        # Adding model 'Scale'
        db.create_table('eyevacs_scale', (
            ('name', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('experiment', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['eyevacs.Experiment'])),
            ('rnd_file', self.gf('django.db.models.fields.related.OneToOneField')(to=orm['eyevacs.External_Source_Data'], unique=True, primary_key=True)),
        ))
        db.send_create_signal('eyevacs', ['Scale'])

        # Adding model 'Scale_Question'
        db.create_table('eyevacs_scale_question', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('linked_scale', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['eyevacs.Scale'])),
            ('text', self.gf('django.db.models.fields.TextField')()),
            ('id_order', self.gf('django.db.models.fields.IntegerField')()),
        ))
        db.send_create_signal('eyevacs', ['Scale_Question'])

        # Adding model 'Grouping'
        db.create_table('eyevacs_grouping', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('experiment', self.gf('django.db.models.fields.related.OneToOneField')(to=orm['eyevacs.Experiment'], unique=True)),
            ('seed', self.gf('django.db.models.fields.IntegerField')()),
            ('counter', self.gf('django.db.models.fields.IntegerField')()),
            ('group_nr', self.gf('django.db.models.fields.TextField')(null=True)),
            ('id_holes', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('id_hole_history', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
        ))
        db.send_create_signal('eyevacs', ['Grouping'])

        # Adding model 'Participant'
        db.create_table('eyevacs_participant', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('experiment', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['eyevacs.Experiment'])),
            ('hard_id', self.gf('django.db.models.fields.IntegerField')()),
            ('def_group', self.gf('django.db.models.fields.CharField')(max_length=3)),
            ('override_group', self.gf('django.db.models.fields.CharField')(max_length=3, blank=True)),
            ('ct_size', self.gf('django.db.models.fields.IntegerField')()),
            ('testpcpt', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('validated_pretest', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('begin_time', self.gf('django.db.models.fields.DateTimeField')()),
            ('end_time', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime.now, blank=True)),
            ('total_time', self.gf('django.db.models.fields.CharField')(default='9999', max_length=100)),
            ('rnd_maxQ1', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('rnd_maxQ2', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('rnd_maxQ3', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('rnd_maxQ4', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('rnd_maxQ5', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('rnd_maxQ6', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('t_rnd_max', self.gf('django.db.models.fields.CharField')(default='9999', max_length=50)),
            ('rnd_regretQ1', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('rnd_regretQ2', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('rnd_regretQ3', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('rnd_regretQ4', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('rnd_regretQ5', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('t_rnd_regret', self.gf('django.db.models.fields.CharField')(default='9999', max_length=50)),
            ('experience_lastvacation', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('experience_planningvacation', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('experience_searchduration', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('t_experience', self.gf('django.db.models.fields.CharField')(default='9999', max_length=50)),
            ('rnd_involvementQ1', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('rnd_involvementQ2', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('rnd_involvementQ3', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('rnd_involvementQ4', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('t_rnd_involvement', self.gf('django.db.models.fields.CharField')(default='9999', max_length=50)),
            ('explanation_distance', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('t_expl_distance', self.gf('django.db.models.fields.CharField')(default='9999', max_length=50)),
            ('explanation_food', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('t_expl_food', self.gf('django.db.models.fields.CharField')(default='9999', max_length=50)),
            ('explanation_price', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('t_expl_price', self.gf('django.db.models.fields.CharField')(default='9999', max_length=50)),
            ('explanation_recommend', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('t_expl_recommend', self.gf('django.db.models.fields.CharField')(default='9999', max_length=50)),
            ('explanation_room', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('t_expl_room', self.gf('django.db.models.fields.CharField')(default='9999', max_length=50)),
            ('explanation_view', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('t_expl_view', self.gf('django.db.models.fields.CharField')(default='9999', max_length=50)),
            ('fav_distance', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('fav_food', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('fav_price', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('fav_recommending', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('fav_room', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('fav_seaview', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('t_expl_fav', self.gf('django.db.models.fields.CharField')(default='9999', max_length=50)),
            ('ct1', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct2', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct3', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct4', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct5', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct6', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct7', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct8', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct9', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct10', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct11', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct12', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct13', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct14', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct15', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct16', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ctamount1', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ctamount2', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ctamount3', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ctamount4', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ctamount5', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ctamount6', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ctamount7', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ctamount8', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ctamount9', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ctamount10', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ctamount11', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ctamount12', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ctamount13', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ctamount14', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ctamount15', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ctamount16', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('cttime1', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('cttime2', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('cttime3', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('cttime4', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('cttime5', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('cttime6', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('cttime7', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('cttime8', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('cttime9', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('cttime10', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('cttime11', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('cttime12', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('cttime13', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('cttime14', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('cttime15', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('cttime16', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('h1conjoint1', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('h1conjoint2', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('h1conjoint3', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('h1conjoint4', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('t_h1page1', self.gf('django.db.models.fields.CharField')(default='9999', max_length=50)),
            ('h1conjoint5', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('h1conjoint6', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('h1conjoint7', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('h1conjoint8', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('t_h1page2', self.gf('django.db.models.fields.CharField')(default='9999', max_length=50)),
            ('h2totaltime', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('h2searchpath', self.gf('django.db.models.fields.TextField')()),
            ('h2durationpath', self.gf('django.db.models.fields.TextField')()),
            ('h2transitdecision', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('t_h2transitdecision', self.gf('django.db.models.fields.CharField')(default='9999', max_length=50)),
            ('rnd_searchgoalsQ1', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('rnd_searchgoalsQ2', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('rnd_searchgoalsQ3', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('rnd_searchgoalsQ4', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('t_rnd_searchgoals', self.gf('django.db.models.fields.CharField')(default='9999', max_length=50)),
            ('rnd_happinessQ1', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('rnd_happinessQ2', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('rnd_happinessQ3', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('rnd_happinessQ4', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('t_rnd_happiness', self.gf('django.db.models.fields.CharField')(default='9999', max_length=50)),
            ('demo_gender', self.gf('django.db.models.fields.CharField')(max_length=6)),
            ('demo_age', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('t_demographics', self.gf('django.db.models.fields.CharField')(default='9999', max_length=50)),
            ('ct1pk', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct1amount', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct1a1', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct1a2', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct1a3', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct1a4', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct1a5', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct2pk', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct2amount', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct2a1', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct2a2', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct2a3', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct2a4', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct2a5', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct3pk', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct3amount', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct3a1', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct3a2', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct3a3', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct3a4', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct3a5', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct4pk', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct4amount', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct4a1', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct4a2', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct4a3', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct4a4', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct4a5', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct5pk', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct5amount', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct5a1', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct5a2', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct5a3', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct5a4', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct5a5', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct6pk', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct6amount', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct6a1', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct6a2', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct6a3', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct6a4', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct6a5', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct7pk', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct7amount', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct7a1', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct7a2', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct7a3', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct7a4', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct7a5', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct8pk', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct8amount', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct8a1', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct8a2', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct8a3', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct8a4', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct8a5', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('ct9pk', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct9amount', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct9a1', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct9a2', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct9a3', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct9a4', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct9a5', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct10pk', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct10amount', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct10a1', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct10a2', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct10a3', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct10a4', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct10a5', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct11pk', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct11amount', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct11a1', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct11a2', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct11a3', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct11a4', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct11a5', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct12pk', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct12amount', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct12a1', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct12a2', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct12a3', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct12a4', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct12a5', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct13pk', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct13amount', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct13a1', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct13a2', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct13a3', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct13a4', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct13a5', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct14pk', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct14amount', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct14a1', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct14a2', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct14a3', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct14a4', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct14a5', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct15pk', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct15amount', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct15a1', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct15a2', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct15a3', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct15a4', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct15a5', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct16pk', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct16amount', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct16a1', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct16a2', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct16a3', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct16a4', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('ct16a5', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('rnd_max_order_pk', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('rnd_max_order', self.gf('django.db.models.fields.TextField')()),
            ('rnd_regret_order_pk', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('rnd_regret_order', self.gf('django.db.models.fields.TextField')()),
            ('rnd_involvement_order_pk', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('rnd_involvement_order', self.gf('django.db.models.fields.TextField')()),
            ('rnd_searchgoals_order_pk', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('rnd_searchgoals_order', self.gf('django.db.models.fields.TextField')()),
            ('rnd_happiness_order_pk', self.gf('django.db.models.fields.CharField')(default='', max_length=100, blank=True)),
            ('rnd_happiness_order', self.gf('django.db.models.fields.TextField')(default='', max_length=100, blank=True)),
            ('raw_timestamps', self.gf('django.db.models.fields.TextField')(default='not assigned')),
        ))
        db.send_create_signal('eyevacs', ['Participant'])


    def backwards(self, orm):
        # Deleting model 'Experiment'
        db.delete_table('eyevacs_experiment')

        # Deleting model 'Pub'
        db.delete_table('eyevacs_pub')

        # Deleting model 'Attribute'
        db.delete_table('eyevacs_attribute')

        # Deleting model 'Level'
        db.delete_table('eyevacs_level')

        # Deleting model 'External_Source_Data'
        db.delete_table('eyevacs_external_source_data')

        # Deleting model 'External_Choice_Task'
        db.delete_table('eyevacs_external_choice_task')

        # Deleting model 'External_Baseline_Choice_Task'
        db.delete_table('eyevacs_external_baseline_choice_task')

        # Deleting model 'External_Order_Scale'
        db.delete_table('eyevacs_external_order_scale')

        # Deleting model 'Scale'
        db.delete_table('eyevacs_scale')

        # Deleting model 'Scale_Question'
        db.delete_table('eyevacs_scale_question')

        # Deleting model 'Grouping'
        db.delete_table('eyevacs_grouping')

        # Deleting model 'Participant'
        db.delete_table('eyevacs_participant')


    models = {
        'eyevacs.attribute': {
            'Meta': {'object_name': 'Attribute'},
            'exp_setup': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['eyevacs.Experiment']"}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'name_de': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True', 'blank': 'True'}),
            'name_en': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True', 'blank': 'True'}),
            'position': ('django.db.models.fields.SmallIntegerField', [], {})
        },
        'eyevacs.experiment': {
            'Meta': {'object_name': 'Experiment'},
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'info': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'language': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '100'})
        },
        'eyevacs.external_baseline_choice_task': {
            'Meta': {'object_name': 'External_Baseline_Choice_Task'},
            'a1': ('django.db.models.fields.CharField', [], {'default': "'empty'", 'max_length': '15'}),
            'a2': ('django.db.models.fields.CharField', [], {'default': "'empty'", 'max_length': '15'}),
            'a3': ('django.db.models.fields.CharField', [], {'default': "'empty'", 'max_length': '15'}),
            'a4': ('django.db.models.fields.CharField', [], {'default': "'empty'", 'max_length': '15'}),
            'a5': ('django.db.models.fields.CharField', [], {'default': "'empty'", 'max_length': '15'}),
            'amount': ('django.db.models.fields.IntegerField', [], {}),
            'ext_src_data': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['eyevacs.External_Source_Data']"}),
            'ext_src_data_name': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'id_hard': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'linked_pcpt': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'Baseline_Choice_TasksAsParticipant'", 'null': 'True', 'to': "orm['eyevacs.Participant']"}),
            'linked_pub': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'Baseline_Choice_TasksAsPub'", 'null': 'True', 'to': "orm['eyevacs.Pub']"}),
            'raw_src_line': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'task': ('django.db.models.fields.IntegerField', [], {}),
            'used': ('django.db.models.fields.BooleanField', [], {'default': 'False'})
        },
        'eyevacs.external_choice_task': {
            'Meta': {'object_name': 'External_Choice_Task'},
            'a1': ('django.db.models.fields.CharField', [], {'default': "'empty'", 'max_length': '15'}),
            'a2': ('django.db.models.fields.CharField', [], {'default': "'empty'", 'max_length': '15'}),
            'a3': ('django.db.models.fields.CharField', [], {'default': "'empty'", 'max_length': '15'}),
            'a4': ('django.db.models.fields.CharField', [], {'default': "'empty'", 'max_length': '15'}),
            'a5': ('django.db.models.fields.CharField', [], {'default': "'empty'", 'max_length': '15'}),
            'a6': ('django.db.models.fields.CharField', [], {'default': "'empty'", 'max_length': '15'}),
            'a7': ('django.db.models.fields.CharField', [], {'default': "'empty'", 'max_length': '15'}),
            'a8': ('django.db.models.fields.CharField', [], {'default': "'empty'", 'max_length': '15'}),
            'amount': ('django.db.models.fields.IntegerField', [], {}),
            'ext_src_data': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['eyevacs.External_Source_Data']"}),
            'ext_src_data_name': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'id_hard': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'linked_pcpt': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'Choice_TasksAsParticipant'", 'null': 'True', 'to': "orm['eyevacs.Participant']"}),
            'linked_pub': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'Choice_TasksAsPub'", 'null': 'True', 'to': "orm['eyevacs.Pub']"}),
            'raw_src_line': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'used': ('django.db.models.fields.BooleanField', [], {'default': 'False'})
        },
        'eyevacs.external_order_scale': {
            'Meta': {'object_name': 'External_Order_Scale'},
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'id_hard': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'linked_pcpt': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['eyevacs.Participant']", 'null': 'True', 'blank': 'True'}),
            'linked_pub': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['eyevacs.Pub']", 'null': 'True', 'blank': 'True'}),
            'scale_rnd_order_ext': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'source_file': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['eyevacs.External_Source_Data']", 'null': 'True', 'blank': 'True'}),
            'used': ('django.db.models.fields.BooleanField', [], {'default': 'False'})
        },
        'eyevacs.external_source_data': {
            'Meta': {'object_name': 'External_Source_Data'},
            'exp_name': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'experiment': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['eyevacs.Experiment']"}),
            'filetype': ('django.db.models.fields.CharField', [], {'max_length': '5'}),
            'header': ('django.db.models.fields.CharField', [], {'max_length': '200'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'info': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'range_end': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'range_start': ('django.db.models.fields.IntegerField', [], {'default': '0'})
        },
        'eyevacs.grouping': {
            'Meta': {'object_name': 'Grouping'},
            'counter': ('django.db.models.fields.IntegerField', [], {}),
            'experiment': ('django.db.models.fields.related.OneToOneField', [], {'to': "orm['eyevacs.Experiment']", 'unique': 'True'}),
            'group_nr': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'id_hole_history': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'id_holes': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'seed': ('django.db.models.fields.IntegerField', [], {})
        },
        'eyevacs.level': {
            'Meta': {'object_name': 'Level'},
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'link_attribute': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['eyevacs.Attribute']"}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'name_de': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True', 'blank': 'True'}),
            'name_en': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True', 'blank': 'True'}),
            'value': ('django.db.models.fields.IntegerField', [], {})
        },
        'eyevacs.participant': {
            'Meta': {'object_name': 'Participant'},
            'begin_time': ('django.db.models.fields.DateTimeField', [], {}),
            'ct1': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct10': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct10a1': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct10a2': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct10a3': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct10a4': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct10a5': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct10amount': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct10pk': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct11': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct11a1': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct11a2': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct11a3': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct11a4': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct11a5': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct11amount': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct11pk': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct12': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct12a1': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct12a2': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct12a3': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct12a4': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct12a5': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct12amount': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct12pk': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct13': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct13a1': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct13a2': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct13a3': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct13a4': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct13a5': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct13amount': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct13pk': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct14': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct14a1': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct14a2': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct14a3': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct14a4': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct14a5': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct14amount': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct14pk': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct15': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct15a1': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct15a2': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct15a3': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct15a4': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct15a5': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct15amount': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct15pk': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct16': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct16a1': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct16a2': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct16a3': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct16a4': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct16a5': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct16amount': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct16pk': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct1a1': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct1a2': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct1a3': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct1a4': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct1a5': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct1amount': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct1pk': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct2': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct2a1': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct2a2': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct2a3': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct2a4': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct2a5': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct2amount': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct2pk': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct3': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct3a1': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct3a2': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct3a3': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct3a4': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct3a5': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct3amount': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct3pk': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct4': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct4a1': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct4a2': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct4a3': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct4a4': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct4a5': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct4amount': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct4pk': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct5': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct5a1': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct5a2': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct5a3': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct5a4': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct5a5': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct5amount': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct5pk': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct6': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct6a1': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct6a2': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct6a3': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct6a4': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct6a5': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct6amount': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct6pk': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct7': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct7a1': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct7a2': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct7a3': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct7a4': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct7a5': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct7amount': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct7pk': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct8': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct8a1': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct8a2': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct8a3': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct8a4': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct8a5': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct8amount': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct8pk': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ct9': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct9a1': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct9a2': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct9a3': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct9a4': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct9a5': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct9amount': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct9pk': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ct_size': ('django.db.models.fields.IntegerField', [], {}),
            'ctamount1': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ctamount10': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ctamount11': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ctamount12': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ctamount13': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ctamount14': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ctamount15': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ctamount16': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'ctamount2': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ctamount3': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ctamount4': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ctamount5': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ctamount6': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ctamount7': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ctamount8': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'ctamount9': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'cttime1': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'cttime10': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'cttime11': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'cttime12': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'cttime13': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'cttime14': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'cttime15': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'cttime16': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'cttime2': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'cttime3': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'cttime4': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'cttime5': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'cttime6': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'cttime7': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'cttime8': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'cttime9': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'def_group': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'demo_age': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'demo_gender': ('django.db.models.fields.CharField', [], {'max_length': '6'}),
            'end_time': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now', 'blank': 'True'}),
            'experience_lastvacation': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'experience_planningvacation': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'experience_searchduration': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'experiment': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['eyevacs.Experiment']"}),
            'explanation_distance': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'explanation_food': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'explanation_price': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'explanation_recommend': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'explanation_room': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'explanation_view': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'fav_distance': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'fav_food': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'fav_price': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'fav_recommending': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'fav_room': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'fav_seaview': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'h1conjoint1': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'h1conjoint2': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'h1conjoint3': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'h1conjoint4': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'h1conjoint5': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'h1conjoint6': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'h1conjoint7': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'h1conjoint8': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'h2durationpath': ('django.db.models.fields.TextField', [], {}),
            'h2searchpath': ('django.db.models.fields.TextField', [], {}),
            'h2totaltime': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'h2transitdecision': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'hard_id': ('django.db.models.fields.IntegerField', [], {}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'override_group': ('django.db.models.fields.CharField', [], {'max_length': '3', 'blank': 'True'}),
            'raw_timestamps': ('django.db.models.fields.TextField', [], {'default': "'not assigned'"}),
            'rnd_happinessQ1': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'rnd_happinessQ2': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'rnd_happinessQ3': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'rnd_happinessQ4': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'rnd_happiness_order': ('django.db.models.fields.TextField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'rnd_happiness_order_pk': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '100', 'blank': 'True'}),
            'rnd_involvementQ1': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'rnd_involvementQ2': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'rnd_involvementQ3': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'rnd_involvementQ4': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'rnd_involvement_order': ('django.db.models.fields.TextField', [], {}),
            'rnd_involvement_order_pk': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'rnd_maxQ1': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'rnd_maxQ2': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'rnd_maxQ3': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'rnd_maxQ4': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'rnd_maxQ5': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'rnd_maxQ6': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'rnd_max_order': ('django.db.models.fields.TextField', [], {}),
            'rnd_max_order_pk': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'rnd_regretQ1': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'rnd_regretQ2': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'rnd_regretQ3': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'rnd_regretQ4': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'rnd_regretQ5': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'rnd_regret_order': ('django.db.models.fields.TextField', [], {}),
            'rnd_regret_order_pk': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'rnd_searchgoalsQ1': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'rnd_searchgoalsQ2': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'rnd_searchgoalsQ3': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'rnd_searchgoalsQ4': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'rnd_searchgoals_order': ('django.db.models.fields.TextField', [], {}),
            'rnd_searchgoals_order_pk': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            't_demographics': ('django.db.models.fields.CharField', [], {'default': "'9999'", 'max_length': '50'}),
            't_experience': ('django.db.models.fields.CharField', [], {'default': "'9999'", 'max_length': '50'}),
            't_expl_distance': ('django.db.models.fields.CharField', [], {'default': "'9999'", 'max_length': '50'}),
            't_expl_fav': ('django.db.models.fields.CharField', [], {'default': "'9999'", 'max_length': '50'}),
            't_expl_food': ('django.db.models.fields.CharField', [], {'default': "'9999'", 'max_length': '50'}),
            't_expl_price': ('django.db.models.fields.CharField', [], {'default': "'9999'", 'max_length': '50'}),
            't_expl_recommend': ('django.db.models.fields.CharField', [], {'default': "'9999'", 'max_length': '50'}),
            't_expl_room': ('django.db.models.fields.CharField', [], {'default': "'9999'", 'max_length': '50'}),
            't_expl_view': ('django.db.models.fields.CharField', [], {'default': "'9999'", 'max_length': '50'}),
            't_h1page1': ('django.db.models.fields.CharField', [], {'default': "'9999'", 'max_length': '50'}),
            't_h1page2': ('django.db.models.fields.CharField', [], {'default': "'9999'", 'max_length': '50'}),
            't_h2transitdecision': ('django.db.models.fields.CharField', [], {'default': "'9999'", 'max_length': '50'}),
            't_rnd_happiness': ('django.db.models.fields.CharField', [], {'default': "'9999'", 'max_length': '50'}),
            't_rnd_involvement': ('django.db.models.fields.CharField', [], {'default': "'9999'", 'max_length': '50'}),
            't_rnd_max': ('django.db.models.fields.CharField', [], {'default': "'9999'", 'max_length': '50'}),
            't_rnd_regret': ('django.db.models.fields.CharField', [], {'default': "'9999'", 'max_length': '50'}),
            't_rnd_searchgoals': ('django.db.models.fields.CharField', [], {'default': "'9999'", 'max_length': '50'}),
            'testpcpt': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'total_time': ('django.db.models.fields.CharField', [], {'default': "'9999'", 'max_length': '100'}),
            'validated_pretest': ('django.db.models.fields.BooleanField', [], {'default': 'False'})
        },
        'eyevacs.pub': {
            'Meta': {'object_name': 'Pub'},
            'create_time': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now', 'blank': 'True'}),
            'csrftoken': ('django.db.models.fields.CharField', [], {'max_length': '150'}),
            'ct_size': ('django.db.models.fields.IntegerField', [], {}),
            'def_group': ('django.db.models.fields.IntegerField', [], {}),
            'experiment': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['eyevacs.Experiment']"}),
            'hard_id': ('django.db.models.fields.IntegerField', [], {}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'override_group': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'sessionid': ('django.db.models.fields.CharField', [], {'max_length': '150'})
        },
        'eyevacs.scale': {
            'Meta': {'object_name': 'Scale'},
            'experiment': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['eyevacs.Experiment']"}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'rnd_file': ('django.db.models.fields.related.OneToOneField', [], {'to': "orm['eyevacs.External_Source_Data']", 'unique': 'True', 'primary_key': 'True'})
        },
        'eyevacs.scale_question': {
            'Meta': {'object_name': 'Scale_Question'},
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'id_order': ('django.db.models.fields.IntegerField', [], {}),
            'linked_scale': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['eyevacs.Scale']"}),
            'text': ('django.db.models.fields.TextField', [], {})
        }
    }

    complete_apps = ['eyevacs']